// Fallback baseline WASH Intelligence dataset for India (Tamil Nadu)
// Ensures the application is 100% operational on Vercel even if a cloud database is not yet connected

export interface DemoCommunity {
  id: string;
  name: string;
  code: string;
  block: string;
  district: string;
  state: string;
  country: string;
  latitude: number;
  longitude: number;
  population: number;
  populationYear: number;
  populationDensity: number;
  waterAccessPct: number;
  waterSourceType: string;
  waterServiceLevel: string;
  waterDataConfidence: string;
  waterReferenceYear: number;
  sanitationAccessPct: number;
  sanitationServiceType: string;
  sanitationReferenceYear: number;
  povertyRate: number;
  socioeconomicSurveyPeriod: string;
  rainfallAnnualMm: number;
  floodHazardLevel: string;
  historicalFloodEvents: number;
  climateReferencePeriod: string;
  infrastructureScore: number;
  waterPointsCount: number;
  functioningWaterPointsCount: number;
  sanitationFacilitiesCount: number;
  infrastructureStatus: string;
  compositeVulnerabilityScore: number;
  vulnerabilityCategory: string;
  dataCompletenessPct: number;
  sourceStatus: string;
  isSampleData: boolean;
  dataLimitationsNotice: string;
  status: string;
  updatedAt: string;
  _count?: {
    interventions: number;
    fieldVerifications: number;
    alerts: number;
  };
}

export const FALLBACK_COMMUNITIES: DemoCommunity[] = [
  {
    id: "comm-01",
    name: "Mandapam Coastal Habitation",
    code: "TN-RAM-01",
    block: "Mandapam",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.2783,
    longitude: 79.1245,
    population: 18200,
    populationYear: 2011,
    populationDensity: 420.0,
    waterAccessPct: 32.5,
    waterSourceType: "Combined Water Supply Scheme (CWSS) & RO Kiosk",
    waterServiceLevel: "Limited Piped Supply",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 48.0,
    sanitationServiceType: "Individual Household Latrine (IHHL)",
    sanitationReferenceYear: 2024,
    povertyRate: 54.2,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 820,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 4,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 38.0,
    waterPointsCount: 24,
    functioningWaterPointsCount: 13,
    sanitationFacilitiesCount: 6,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 78.4,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 2, fieldVerifications: 1, alerts: 2 }
  },
  {
    id: "comm-02",
    name: "Tiruvadanai Agrarian Panchayat",
    code: "TN-RAM-02",
    block: "Tiruvadanai",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.7891,
    longitude: 78.9124,
    population: 24500,
    populationYear: 2011,
    populationDensity: 310.0,
    waterAccessPct: 38.0,
    waterSourceType: "Deep Borewell with OHT & Open Ooranis",
    waterServiceLevel: "Unimproved / High Total Dissolved Solids",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 52.0,
    sanitationServiceType: "Twin-Pit Pour Flush Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 58.0,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 890,
    floodHazardLevel: "High",
    historicalFloodEvents: 3,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 42.0,
    waterPointsCount: 32,
    functioningWaterPointsCount: 19,
    sanitationFacilitiesCount: 8,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 72.1,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 1, fieldVerifications: 1, alerts: 1 }
  },
  {
    id: "comm-03",
    name: "Mudukulathur Drought Basin",
    code: "TN-RAM-03",
    block: "Mudukulathur",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.3421,
    longitude: 78.5123,
    population: 29800,
    populationYear: 2011,
    populationDensity: 295.0,
    waterAccessPct: 29.0,
    waterSourceType: "Cauvery Integrated Pipeline Extension",
    waterServiceLevel: "Intermittent Tank Supply",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 44.0,
    sanitationServiceType: "Individual Household Latrine (IHHL)",
    sanitationReferenceYear: 2024,
    povertyRate: 62.5,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 740,
    floodHazardLevel: "Moderate",
    historicalFloodEvents: 1,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 32.0,
    waterPointsCount: 38,
    functioningWaterPointsCount: 16,
    sanitationFacilitiesCount: 5,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 79.8,
    vulnerabilityCategory: "VERY_HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 2, fieldVerifications: 0, alerts: 1 }
  },
  {
    id: "comm-04",
    name: "Kilakarai Coastal Habitation",
    code: "TN-RAM-04",
    block: "Kilakarai",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.2312,
    longitude: 78.7845,
    population: 38400,
    populationYear: 2011,
    populationDensity: 850.0,
    waterAccessPct: 45.0,
    waterSourceType: "Desalination Plant & TWAD Piped Feed",
    waterServiceLevel: "Basic Piped Connection",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 64.0,
    sanitationServiceType: "Septic Tank with Soak Pit",
    sanitationReferenceYear: 2024,
    povertyRate: 41.0,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 860,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 3,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 54.0,
    waterPointsCount: 42,
    functioningWaterPointsCount: 31,
    sanitationFacilitiesCount: 14,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 61.2,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 1, fieldVerifications: 1, alerts: 0 }
  },
  {
    id: "comm-05",
    name: "Paramakudi Riverine Cluster",
    code: "TN-RAM-05",
    block: "Paramakudi",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.5432,
    longitude: 78.5912,
    population: 52000,
    populationYear: 2011,
    populationDensity: 620.0,
    waterAccessPct: 56.0,
    waterSourceType: "Vaigai River Bed Subsurface Collector Well",
    waterServiceLevel: "Basic",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 61.0,
    sanitationServiceType: "Piped Sewerage / Septic",
    sanitationReferenceYear: 2024,
    povertyRate: 46.0,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 810,
    floodHazardLevel: "High",
    historicalFloodEvents: 2,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 61.0,
    waterPointsCount: 56,
    functioningWaterPointsCount: 44,
    sanitationFacilitiesCount: 18,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 52.4,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 0, fieldVerifications: 0, alerts: 0 }
  },
  {
    id: "comm-06",
    name: "Parangipettai Estuary Village",
    code: "TN-CUD-06",
    block: "Parangipettai",
    district: "Cuddalore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.4982,
    longitude: 79.7645,
    population: 32500,
    populationYear: 2011,
    populationDensity: 690.0,
    waterAccessPct: 41.0,
    waterSourceType: "Vellar River Subsurface Infiltration Scheme",
    waterServiceLevel: "Limited / Estuary Saline Intrusion",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 50.0,
    sanitationServiceType: "IHHL & Community Complex",
    sanitationReferenceYear: 2024,
    povertyRate: 51.5,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 1350,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 5,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 40.0,
    waterPointsCount: 36,
    functioningWaterPointsCount: 21,
    sanitationFacilitiesCount: 9,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 74.6,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 1, fieldVerifications: 1, alerts: 1 }
  },
  {
    id: "comm-07",
    name: "Chidambaram Rural Habitations",
    code: "TN-CUD-07",
    block: "Chidambaram",
    district: "Cuddalore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.3991,
    longitude: 79.6934,
    population: 46200,
    populationYear: 2011,
    populationDensity: 740.0,
    waterAccessPct: 58.0,
    waterSourceType: "Kollidam River Deep Borewell Collector Wells",
    waterServiceLevel: "Basic Tap Water",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 62.0,
    sanitationServiceType: "Pour-Flush Septic System",
    sanitationReferenceYear: 2024,
    povertyRate: 45.0,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 1280,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 4,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 58.0,
    waterPointsCount: 52,
    functioningWaterPointsCount: 42,
    sanitationFacilitiesCount: 16,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 58.5,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 0, fieldVerifications: 0, alerts: 0 }
  },
  {
    id: "comm-08",
    name: "Kurinjipadi Inland Panchayat",
    code: "TN-CUD-08",
    block: "Kurinjipadi",
    district: "Cuddalore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.5643,
    longitude: 79.6012,
    population: 35400,
    populationYear: 2011,
    populationDensity: 480.0,
    waterAccessPct: 53.0,
    waterSourceType: "Cuddalore Sandstone Deep Aquifer",
    waterServiceLevel: "Basic",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 58.0,
    sanitationServiceType: "Twin-Pit Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 48.0,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 1150,
    floodHazardLevel: "Moderate",
    historicalFloodEvents: 2,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 52.0,
    waterPointsCount: 40,
    functioningWaterPointsCount: 30,
    sanitationFacilitiesCount: 11,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 54.2,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 0, fieldVerifications: 0, alerts: 0 }
  },
  {
    id: "comm-09",
    name: "Vedaranyam Salt Pan Panchayat",
    code: "TN-NAG-09",
    block: "Vedaranyam",
    district: "Nagapattinam",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.3721,
    longitude: 79.8512,
    population: 34200,
    populationYear: 2011,
    populationDensity: 510.0,
    waterAccessPct: 26.0,
    waterSourceType: "Deep Sand Dune Freshwater Lenses & Tankers",
    waterServiceLevel: "Unimproved / Highly Saline",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 41.0,
    sanitationServiceType: "Individual Household Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 64.0,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 1420,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 6,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 28.0,
    waterPointsCount: 30,
    functioningWaterPointsCount: 11,
    sanitationFacilitiesCount: 5,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 84.7,
    vulnerabilityCategory: "VERY_HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 2, fieldVerifications: 1, alerts: 2 }
  },
  {
    id: "comm-10",
    name: "Tharangambadi Coastal Hamlet",
    code: "TN-MAY-10",
    block: "Tharangambadi",
    district: "Mayiladuthurai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.0289,
    longitude: 79.8543,
    population: 27800,
    populationYear: 2011,
    populationDensity: 650.0,
    waterAccessPct: 48.0,
    waterSourceType: "Cauvery Tail-End CWSS Pipeline",
    waterServiceLevel: "Limited",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 56.0,
    sanitationServiceType: "Pour-Flush to Septic",
    sanitationReferenceYear: 2024,
    povertyRate: 47.0,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 1310,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 4,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 49.0,
    waterPointsCount: 35,
    functioningWaterPointsCount: 24,
    sanitationFacilitiesCount: 10,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 66.8,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 1, fieldVerifications: 0, alerts: 1 }
  },
  {
    id: "comm-11",
    name: "Pennagaram Fluorosis Belt",
    code: "TN-DHA-11",
    block: "Pennagaram",
    district: "Dharmapuri",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.1342,
    longitude: 77.8921,
    population: 38900,
    populationYear: 2011,
    populationDensity: 390.0,
    waterAccessPct: 36.0,
    waterSourceType: "Hogenakkal Drinking Water Fluorosis Mitigation Scheme",
    waterServiceLevel: "Treated Fluoride-Safe Tap Water",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 49.0,
    sanitationServiceType: "IHHL Rural Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 59.0,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 850,
    floodHazardLevel: "Low",
    historicalFloodEvents: 0,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 44.0,
    waterPointsCount: 44,
    functioningWaterPointsCount: 26,
    sanitationFacilitiesCount: 9,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 68.2,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 1, fieldVerifications: 1, alerts: 1 }
  },
  {
    id: "comm-12",
    name: "Polur Hard-Rock Habitation",
    code: "TN-TIR-12",
    block: "Polur",
    district: "Tiruvannamalai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.5123,
    longitude: 79.1245,
    population: 31500,
    populationYear: 2011,
    populationDensity: 440.0,
    waterAccessPct: 42.0,
    waterSourceType: "Cheyyar River Infiltration & Borewells",
    waterServiceLevel: "Basic Tap Water",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 51.0,
    sanitationServiceType: "Individual Household Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 53.0,
    socioeconomicSurveyPeriod: "NFHS-5 (2019-2021)",
    rainfallAnnualMm: 1020,
    floodHazardLevel: "Moderate",
    historicalFloodEvents: 1,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 50.0,
    waterPointsCount: 39,
    functioningWaterPointsCount: 27,
    sanitationFacilitiesCount: 11,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 59.3,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    dataLimitationsNotice: "Illustrative demo baseline — not official or live telemetry",
    status: "ACTIVE",
    updatedAt: new Date().toISOString(),
    _count: { interventions: 0, fieldVerifications: 0, alerts: 0 }
  }
];

export const FALLBACK_ANALYTICS = {
  summary: {
    analyzedCommunitiesCount: 12,
    totalPopulation: 409500,
    populationInadequateWater: 243500,
    populationInadequateSanitation: 195200,
    highVulnerabilityCount: 7,
    significantFloodExposureCount: 8,
    incompleteDatasetsCount: 0,
    pendingVerifications: 3,
    activeInterventions: 8,
    activeAlerts: 8
  },
  districtStats: [
    {
      district: "Ramanathapuram",
      region: "Ramanathapuram",
      communitiesCount: 5,
      population: 162900,
      averageWaterAccess: 40.1,
      averageSanitationAccess: 53.8,
      averageVulnerability: 68.8,
      highVulnerabilityCount: 4
    },
    {
      district: "Cuddalore",
      region: "Cuddalore",
      communitiesCount: 3,
      population: 114100,
      averageWaterAccess: 50.7,
      averageSanitationAccess: 54.0,
      averageVulnerability: 62.4,
      highVulnerabilityCount: 1
    },
    {
      district: "Nagapattinam",
      region: "Nagapattinam",
      communitiesCount: 1,
      population: 34200,
      averageWaterAccess: 26.0,
      averageSanitationAccess: 41.0,
      averageVulnerability: 84.7,
      highVulnerabilityCount: 1
    },
    {
      district: "Mayiladuthurai",
      region: "Mayiladuthurai",
      communitiesCount: 1,
      population: 27800,
      averageWaterAccess: 48.0,
      averageSanitationAccess: 56.0,
      averageVulnerability: 66.8,
      highVulnerabilityCount: 1
    },
    {
      district: "Dharmapuri",
      region: "Dharmapuri",
      communitiesCount: 1,
      population: 38900,
      averageWaterAccess: 36.0,
      averageSanitationAccess: 49.0,
      averageVulnerability: 68.2,
      highVulnerabilityCount: 1
    },
    {
      district: "Tiruvannamalai",
      region: "Tiruvannamalai",
      communitiesCount: 1,
      population: 31500,
      averageWaterAccess: 42.0,
      averageSanitationAccess: 51.0,
      averageVulnerability: 59.3,
      highVulnerabilityCount: 0
    }
  ],
  riskFactorAverages: [
    { name: "Water Access Gap (JJM Tap Coverage)", averageScore: 60, weight: 25, color: "#06b6d4", source: "Jal Jeevan Mission / WQMIS" },
    { name: "Sanitation Access Gap (SBM-G Coverage)", averageScore: 47, weight: 20, color: "#3b82f6", source: "Swachh Bharat Mission (Grameen)" },
    { name: "Climate & Flood Exposure (IMD & CWC)", averageScore: 68, weight: 20, color: "#f97316", source: "India Meteorological Dept / CWC" },
    { name: "Socioeconomic Deprivation (NFHS-5)", averageScore: 53, weight: 15, color: "#eab308", source: "NFHS-5 (2019-2021) / NITI Aayog" },
    { name: "Infrastructure Fragility (TWAD Board)", averageScore: 54, weight: 10, color: "#ef4444", source: "Tamil Nadu Water Supply & Drainage Board" },
    { name: "Population Vulnerability (Census 2011)", averageScore: 48, weight: 10, color: "#8b5cf6", source: "Census of India 2011" },
  ],
  vulnerabilityDistribution: [
    { category: "VERY_HIGH", count: 2, label: "Very High (≥75)" },
    { category: "HIGH", count: 5, label: "High (60-74)" },
    { category: "MODERATE", count: 5, label: "Moderate (40-59)" },
    { category: "LOW", count: 0, label: "Low (20-39)" },
    { category: "VERY_LOW", count: 0, label: "Very Low (<20)" }
  ],
  priorityCommunities: FALLBACK_COMMUNITIES.slice(0, 5)
};

export const FALLBACK_COMPLAINTS = [
  {
    id: "cmp-01",
    complaintNumber: "CMP-2026-0001",
    trackingId: "AQUA-TN-RAM-0001",
    title: "Main RO Plant Filter Clogging & Brackish Water Output",
    description: "Community RO plant membrane fouled after tidal surge. Water has high salinity (TDS > 1800 ppm) and yellow sediment. Over 3,000 residents forced to purchase private tanker water.",
    category: "WATER_QUALITY",
    status: "IN_PROGRESS",
    priority: "HIGH",
    priorityReason: "Critical drinking water source in high-vulnerability coastal community (Mandapam); affects large population.",
    locationName: "South Fishermen Colony, Ward 3, Mandapam",
    latitude: 9.2785,
    longitude: 79.1248,
    communityId: "comm-01",
    reporterName: "K. Murugesan",
    reporterContact: "+91 98421 77652",
    isAnonymous: false,
    assignedOfficerName: "M. Subramanian, Assistant Engineer",
    verificationStatus: "VERIFIED",
    isSampleData: true,
    createdAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    community: {
      id: "comm-01",
      name: "Mandapam Coastal Habitation",
      code: "TN-RAM-01",
      district: "Ramanathapuram",
      block: "Mandapam",
      state: "Tamil Nadu",
      compositeVulnerabilityScore: 78.4
    },
    evidence: [
      {
        id: "ev-01",
        fileUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb1861593?w=800&auto=format&fit=crop",
        caption: "Fouled pre-filter cartridges and turbid discharge from community RO kiosk",
        fileType: "image"
      }
    ],
    statusHistory: [
      {
        id: "sh-01",
        oldStatus: "NONE",
        newStatus: "REPORTED",
        changedByName: "K. Murugesan (Citizen)",
        notes: "Grievance submitted via Aqua-Lens Citizen Portal.",
        createdAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString()
      },
      {
        id: "sh-02",
        oldStatus: "REPORTED",
        newStatus: "IN_PROGRESS",
        changedByName: "M. Subramanian, Assistant Engineer",
        notes: "Field inspection completed; membrane replacement requisition submitted.",
        createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString()
      }
    ]
  },
  {
    id: "cmp-02",
    complaintNumber: "CMP-2026-0002",
    trackingId: "AQUA-TN-RAM-0002",
    title: "Pipeline Rupture under Beach Road - Contaminated Seepage",
    description: "Main potable distribution line ruptured near drainage culvert. Drain runoff is siphoning into drinking pipeline during low pressure cycles.",
    category: "WATER_SUPPLY",
    status: "ASSIGNED",
    priority: "CRITICAL",
    priorityReason: "Direct sewage-drinking water cross contamination hazard; immediate epidemic risk.",
    locationName: "Beach Road near Fish Landing Center, Mandapam",
    latitude: 9.2790,
    longitude: 79.1252,
    communityId: "comm-01",
    reporterName: "S. Annamalai",
    reporterContact: "+91 97892 44310",
    isAnonymous: false,
    assignedOfficerName: "M. Subramanian, Assistant Engineer",
    verificationStatus: "UNDER_REVIEW",
    isSampleData: true,
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    community: {
      id: "comm-01",
      name: "Mandapam Coastal Habitation",
      code: "TN-RAM-01",
      district: "Ramanathapuram",
      block: "Mandapam",
      state: "Tamil Nadu",
      compositeVulnerabilityScore: 78.4
    },
    evidence: [],
    statusHistory: []
  },
  {
    id: "cmp-03",
    complaintNumber: "CMP-2026-0003",
    trackingId: "AQUA-TN-NAG-0003",
    title: "Seawater Intrusion in Ward 4 Borewell after High Tide Surge",
    description: "Salinity in municipal borewell rose drastically following spring tide surge. Conductivity exceeds 3200 µS/cm. Inhabitants having skin irritation.",
    category: "WATER_QUALITY",
    status: "INVESTIGATING",
    priority: "CRITICAL",
    priorityReason: "Complete loss of freshwater aquifer access in highest-risk coastal block (Vedaranyam).",
    locationName: "Ward 4 Salt Pan Enclave, Vedaranyam",
    latitude: 10.3725,
    longitude: 79.8515,
    communityId: "comm-09",
    reporterName: "R. Jayachandran",
    reporterContact: "+91 94432 10987",
    isAnonymous: false,
    assignedOfficerName: "M. Subramanian, Assistant Engineer",
    verificationStatus: "VERIFIED",
    isSampleData: true,
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    community: {
      id: "comm-09",
      name: "Vedaranyam Salt Pan Panchayat",
      code: "TN-NAG-09",
      district: "Nagapattinam",
      block: "Vedaranyam",
      state: "Tamil Nadu",
      compositeVulnerabilityScore: 84.7
    },
    evidence: [],
    statusHistory: []
  }
];

export const FALLBACK_DATA_SOURCES = [
  {
    id: "ds-01",
    sourceAgency: "Ministry of Jal Shakti, Government of India",
    officialUrl: "https://ejalshakti.gov.in/WQMIS",
    datasetTitle: "Jal Jeevan Mission (JJM) Har Ghar Jal & WQMIS Portal",
    indicatorName: "Functional Household Tap Connection (FHTC) & Water Quality",
    indicatorDefinition: "Percentage of rural households provided with individual piped potable tap water connections (55 LPCD standard) and verified laboratory water quality testing.",
    geographicLevel: "State / District / Block / Gram Panchayat",
    referencePeriod: "2024-2025",
    units: "% of households",
    sourceStatus: "Official",
    confidenceNote: "Official Government of India portal data baseline.",
    category: "WATER_ACCESS",
    lastUpdated: new Date().toISOString()
  },
  {
    id: "ds-02",
    sourceAgency: "Office of the Registrar General & Census Commissioner, India (ORGI)",
    officialUrl: "https://censusindia.gov.in/census.website/en",
    datasetTitle: "Census of India 2011 Primary Census Abstract & Household Table H-8",
    indicatorName: "Village Population & Household Drinking Water Source Distribution",
    indicatorDefinition: "Official decennial count of village/town resident population and proportion of households with treated tap water, handpumps, and wells.",
    geographicLevel: "District / Sub-District / Village / Ward",
    referencePeriod: "Census 2011",
    units: "Count of persons / households",
    sourceStatus: "Official",
    confidenceNote: "Official Census 2011 baseline data.",
    category: "POPULATION",
    lastUpdated: new Date().toISOString()
  },
  {
    id: "ds-03",
    sourceAgency: "Department of Drinking Water & Sanitation, Ministry of Jal Shakti (OGD India)",
    officialUrl: "https://www.data.gov.in/catalog/daily-data-rural-sanitation-coverage-under-swachh-bharat-mission",
    datasetTitle: "Swachh Bharat Mission (Grameen) Rural Sanitation Coverage",
    indicatorName: "Individual Household Latrine (IHHL) Coverage & ODF Plus Status",
    indicatorDefinition: "Percentage of rural households with access to sanitary individual latrines, community sanitary complexes (CSC), and solid/liquid waste management.",
    geographicLevel: "District / Block / Gram Panchayat",
    referencePeriod: "2024",
    units: "% coverage",
    sourceStatus: "Official",
    confidenceNote: "Open Government Data (OGD) catalog.",
    category: "SANITATION",
    lastUpdated: new Date().toISOString()
  },
  {
    id: "ds-04",
    sourceAgency: "India Meteorological Department (IMD), Ministry of Earth Sciences",
    officialUrl: "https://mausam.imd.gov.in/",
    datasetTitle: "IMD District Rainfall Climatology & Daily Gridded Precipitation",
    indicatorName: "Normal Annual Precipitation & Monsoon Rainfall Deviation",
    indicatorDefinition: "Long-period average annual precipitation (mm) and southwest/northeast monsoon departure indices.",
    geographicLevel: "District / Meteorological Sub-Division",
    referencePeriod: "1981-2020 Normal",
    units: "mm per year",
    sourceStatus: "Official",
    confidenceNote: "Official IMD meteorological normal.",
    category: "CLIMATE_FLOOD",
    lastUpdated: new Date().toISOString()
  },
  {
    id: "ds-05",
    sourceAgency: "Central Water Commission (CWC) & Tamil Nadu SDMA",
    officialUrl: "https://cwc.gov.in/",
    datasetTitle: "National Hydrological River Basin Flood Atlas & Cyclone Inundation Hazard",
    indicatorName: "Hydrological Flood Hazard Level & Inundation Risk Band",
    indicatorDefinition: "Multi-year hydrological return period flood hazard categorization (Low, Moderate, High, Severe) for riverine delta and coastal surge zones.",
    geographicLevel: "Basin / District / Coastal Taluk",
    referencePeriod: "2020-2024",
    units: "Risk Classification (Low/Moderate/High/Severe)",
    sourceStatus: "Official",
    confidenceNote: "Official hydrological survey.",
    category: "CLIMATE_FLOOD",
    lastUpdated: new Date().toISOString()
  }
];
