export type MonitoringStationStatus = "ONLINE" | "WARNING" | "OFFLINE";

export interface SensorReadings {
  status: MonitoringStationStatus;
  lastTransmission: string;
  isSimulatedDemo: true; // Explicitly marked as demo data (never claimed as live)
  ph: number | null;
  phStatus?: "NORMAL" | "HIGH" | "LOW";
  tdsPpm: number | null;
  tdsStatus?: "NORMAL" | "ELEVATED" | "CRITICAL";
  turbidityNtu: number | null;
  turbidityStatus?: "NORMAL" | "HIGH";
  chlorineResidualMgL: number | null;
  waterLevelDepthM: number | null;
  flowRateM3Hr: number | null;
  fluorideMgL?: number | null;
  batteryPct?: number | null;
  signalStrengthDbm?: number | null;
  alertRemarks?: string;
}

export interface WaterMonitoringStation {
  id: string;
  name: string;
  code: string;
  type:
    | "Groundwater Telemetry Well"
    | "River & Estuary Gauge"
    | "Water Treatment / RO Plant"
    | "Overhead Tank (OHT) Sensor Node"
    | "Coastal Salinity Ingress Station"
    | "Fluoride Surveillance Node";
  state: string;
  district: string;
  block?: string;
  latitude: number;
  longitude: number;
  status: MonitoringStationStatus;
  installYear: number;
  readings: SensorReadings;
}

export const WATER_MONITORING_STATIONS: WaterMonitoringStation[] = [
  // --- Tamil Nadu Pilot Network (High-Density) ---
  {
    id: "wms-ram-01",
    code: "WMS-TN-RAM-01",
    name: "Mandapam Coastal RO & Desalination Station",
    type: "Coastal Salinity Ingress Station",
    state: "Tamil Nadu",
    district: "Ramanathapuram",
    block: "Mandapam",
    latitude: 9.281,
    longitude: 79.1235,
    status: "WARNING",
    installYear: 2022,
    readings: {
      status: "WARNING",
      lastTransmission: "Today 10:45 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.9,
      phStatus: "NORMAL",
      tdsPpm: 1480,
      tdsStatus: "ELEVATED",
      turbidityNtu: 1.2,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.18,
      waterLevelDepthM: 2.8,
      flowRateM3Hr: 18.5,
      batteryPct: 88,
      signalStrengthDbm: -72,
      alertRemarks: "Elevated TDS due to coastal tidal salinity ingress into shallow intake.",
    },
  },
  {
    id: "wms-ram-02",
    code: "WMS-TN-RAM-02",
    name: "Tiruvadanai Aquifer Telemetry Well",
    type: "Groundwater Telemetry Well",
    state: "Tamil Nadu",
    district: "Ramanathapuram",
    block: "Tiruvadanai",
    latitude: 9.789,
    longitude: 78.916,
    status: "ONLINE",
    installYear: 2021,
    readings: {
      status: "ONLINE",
      lastTransmission: "Today 11:15 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.2,
      phStatus: "NORMAL",
      tdsPpm: 540,
      tdsStatus: "NORMAL",
      turbidityNtu: 0.8,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.22,
      waterLevelDepthM: 14.5,
      flowRateM3Hr: 32.0,
      batteryPct: 94,
      signalStrengthDbm: -68,
    },
  },
  {
    id: "wms-ram-03",
    code: "WMS-TN-RAM-03",
    name: "Mudukulathur Drought Basin Sensor Node",
    type: "Overhead Tank (OHT) Sensor Node",
    state: "Tamil Nadu",
    district: "Ramanathapuram",
    block: "Mudukulathur",
    latitude: 9.345,
    longitude: 78.508,
    status: "OFFLINE",
    installYear: 2020,
    readings: {
      status: "OFFLINE",
      lastTransmission: "Yesterday 04:30 PM (Signal Lost)",
      isSimulatedDemo: true,
      ph: null,
      tdsPpm: null,
      turbidityNtu: null,
      chlorineResidualMgL: null,
      waterLevelDepthM: null,
      flowRateM3Hr: 0,
      batteryPct: 12,
      signalStrengthDbm: -110,
      alertRemarks: "Telemetry offline: Low solar battery charge and intermittent cellular connectivity.",
    },
  },
  {
    id: "wms-cud-01",
    code: "WMS-TN-CUD-01",
    name: "Parangipettai Vellar Estuary Hydrological Gauge",
    type: "River & Estuary Gauge",
    state: "Tamil Nadu",
    district: "Cuddalore",
    block: "Porto Novo",
    latitude: 11.498,
    longitude: 79.764,
    status: "WARNING",
    installYear: 2023,
    readings: {
      status: "WARNING",
      lastTransmission: "Today 11:00 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.8,
      phStatus: "NORMAL",
      tdsPpm: 1120,
      tdsStatus: "ELEVATED",
      turbidityNtu: 6.4,
      turbidityStatus: "HIGH",
      chlorineResidualMgL: 0.12,
      waterLevelDepthM: 1.2,
      flowRateM3Hr: 54.0,
      batteryPct: 91,
      signalStrengthDbm: -70,
      alertRemarks: "High turbidity caused by agricultural upstream runoff following monsoon shower.",
    },
  },
  {
    id: "wms-cud-02",
    code: "WMS-TN-CUD-02",
    name: "Cuddalore Old Town Industrial Perimeter Station",
    type: "Water Treatment / RO Plant",
    state: "Tamil Nadu",
    district: "Cuddalore",
    block: "Cuddalore",
    latitude: 11.745,
    longitude: 79.775,
    status: "ONLINE",
    installYear: 2022,
    readings: {
      status: "ONLINE",
      lastTransmission: "Today 10:30 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.3,
      phStatus: "NORMAL",
      tdsPpm: 620,
      tdsStatus: "NORMAL",
      turbidityNtu: 1.5,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.28,
      waterLevelDepthM: 5.4,
      flowRateM3Hr: 45.0,
      batteryPct: 97,
      signalStrengthDbm: -65,
    },
  },
  {
    id: "wms-cud-03",
    code: "WMS-TN-CUD-03",
    name: "Kurinjipadi Groundwater Observation Well",
    type: "Groundwater Telemetry Well",
    state: "Tamil Nadu",
    district: "Cuddalore",
    block: "Kurinjipadi",
    latitude: 11.568,
    longitude: 79.601,
    status: "ONLINE",
    installYear: 2021,
    readings: {
      status: "ONLINE",
      lastTransmission: "Today 11:20 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.1,
      phStatus: "NORMAL",
      tdsPpm: 430,
      tdsStatus: "NORMAL",
      turbidityNtu: 0.6,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.25,
      waterLevelDepthM: 8.9,
      flowRateM3Hr: 28.0,
      batteryPct: 89,
      signalStrengthDbm: -74,
    },
  },
  {
    id: "wms-nag-01",
    code: "WMS-TN-NAG-01",
    name: "Vedaranyam Salt Swamp Coastal Monitoring Node",
    type: "Coastal Salinity Ingress Station",
    state: "Tamil Nadu",
    district: "Nagapattinam",
    block: "Vedaranyam",
    latitude: 10.372,
    longitude: 79.851,
    status: "WARNING",
    installYear: 2022,
    readings: {
      status: "WARNING",
      lastTransmission: "Today 09:50 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 8.3,
      phStatus: "HIGH",
      tdsPpm: 2150,
      tdsStatus: "CRITICAL",
      turbidityNtu: 2.1,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.1,
      waterLevelDepthM: 1.8,
      flowRateM3Hr: 12.0,
      batteryPct: 85,
      signalStrengthDbm: -78,
      alertRemarks: "Severe brackish intrusion in shallow coastal aquifer. TDS exceeds 2,000 ppm threshold.",
    },
  },
  {
    id: "wms-nag-02",
    code: "WMS-TN-NAG-02",
    name: "Nagapattinam Fish Harbor Public Scheme Node",
    type: "Overhead Tank (OHT) Sensor Node",
    state: "Tamil Nadu",
    district: "Nagapattinam",
    block: "Nagapattinam",
    latitude: 10.765,
    longitude: 79.845,
    status: "ONLINE",
    installYear: 2023,
    readings: {
      status: "ONLINE",
      lastTransmission: "Today 11:10 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.4,
      phStatus: "NORMAL",
      tdsPpm: 480,
      tdsStatus: "NORMAL",
      turbidityNtu: 0.9,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.3,
      waterLevelDepthM: 4.2,
      flowRateM3Hr: 38.0,
      batteryPct: 96,
      signalStrengthDbm: -62,
    },
  },
  {
    id: "wms-may-01",
    code: "WMS-TN-MAY-01",
    name: "Mayiladuthurai Cauvery Tail-End Barrage Station",
    type: "River & Estuary Gauge",
    state: "Tamil Nadu",
    district: "Mayiladuthurai",
    block: "Mayiladuthurai",
    latitude: 11.109,
    longitude: 79.655,
    status: "ONLINE",
    installYear: 2021,
    readings: {
      status: "ONLINE",
      lastTransmission: "Today 11:25 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.5,
      phStatus: "NORMAL",
      tdsPpm: 390,
      tdsStatus: "NORMAL",
      turbidityNtu: 1.8,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.24,
      waterLevelDepthM: 6.1,
      flowRateM3Hr: 65.0,
      batteryPct: 92,
      signalStrengthDbm: -69,
    },
  },
  {
    id: "wms-dha-01",
    code: "WMS-TN-DHA-01",
    name: "Pennagaram Fluoride Automated Surveillance Node",
    type: "Fluoride Surveillance Node",
    state: "Tamil Nadu",
    district: "Dharmapuri",
    block: "Pennagaram",
    latitude: 12.138,
    longitude: 77.905,
    status: "WARNING",
    installYear: 2022,
    readings: {
      status: "WARNING",
      lastTransmission: "Today 10:15 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.6,
      phStatus: "NORMAL",
      tdsPpm: 890,
      tdsStatus: "NORMAL",
      turbidityNtu: 0.7,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.2,
      waterLevelDepthM: 22.4,
      flowRateM3Hr: 24.0,
      fluorideMgL: 2.4,
      batteryPct: 90,
      signalStrengthDbm: -75,
      alertRemarks: "Fluoride level (2.4 mg/L) exceeds WHO and BIS permissible limit of 1.5 mg/L.",
    },
  },
  {
    id: "wms-tir-01",
    code: "WMS-TN-TIR-01",
    name: "Chengam Drought Basin Deep Piezometer",
    type: "Groundwater Telemetry Well",
    state: "Tamil Nadu",
    district: "Tiruvannamalai",
    block: "Chengam",
    latitude: 12.308,
    longitude: 78.895,
    status: "WARNING",
    installYear: 2021,
    readings: {
      status: "WARNING",
      lastTransmission: "Today 10:55 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.4,
      phStatus: "NORMAL",
      tdsPpm: 710,
      tdsStatus: "NORMAL",
      turbidityNtu: 1.1,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.15,
      waterLevelDepthM: 28.5,
      flowRateM3Hr: 16.0,
      batteryPct: 83,
      signalStrengthDbm: -80,
      alertRemarks: "Severe water table depletion: Piezometer depth reached 28.5 m below ground level.",
    },
  },
  {
    id: "wms-tir-02",
    code: "WMS-TN-TIR-02",
    name: "Polur Agricultural Water Supply Node",
    type: "Overhead Tank (OHT) Sensor Node",
    state: "Tamil Nadu",
    district: "Tiruvannamalai",
    block: "Polur",
    latitude: 12.502,
    longitude: 79.124,
    status: "OFFLINE",
    installYear: 2020,
    readings: {
      status: "OFFLINE",
      lastTransmission: "3 days ago (Telemetry Fault)",
      isSimulatedDemo: true,
      ph: null,
      tdsPpm: null,
      turbidityNtu: null,
      chlorineResidualMgL: null,
      waterLevelDepthM: null,
      flowRateM3Hr: 0,
      batteryPct: 0,
      signalStrengthDbm: null,
      alertRemarks: "Telemetry offline: Sensor array replacement required.",
    },
  },

  // --- National Basins Network (Pan-India Reference Stations) ---
  {
    id: "wms-nat-01",
    code: "WMS-IN-JK-01",
    name: "Jhelum Basin Glacial Melt & Quality Station (Srinagar)",
    type: "River & Estuary Gauge",
    state: "Jammu and Kashmir",
    district: "Srinagar",
    latitude: 34.0837,
    longitude: 74.7973,
    status: "ONLINE",
    installYear: 2023,
    readings: {
      status: "ONLINE",
      lastTransmission: "Today 10:00 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.5,
      phStatus: "NORMAL",
      tdsPpm: 180,
      tdsStatus: "NORMAL",
      turbidityNtu: 1.1,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.2,
      waterLevelDepthM: 4.8,
      flowRateM3Hr: 110.0,
      batteryPct: 95,
      signalStrengthDbm: -64,
    },
  },
  {
    id: "wms-nat-02",
    code: "WMS-IN-UP-01",
    name: "Ganga Central Basin Hydrological Node (Varanasi)",
    type: "River & Estuary Gauge",
    state: "Uttar Pradesh",
    district: "Varanasi",
    latitude: 25.3176,
    longitude: 82.9739,
    status: "WARNING",
    installYear: 2022,
    readings: {
      status: "WARNING",
      lastTransmission: "Today 11:05 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.9,
      phStatus: "NORMAL",
      tdsPpm: 580,
      tdsStatus: "NORMAL",
      turbidityNtu: 4.8,
      turbidityStatus: "HIGH",
      chlorineResidualMgL: 0.15,
      waterLevelDepthM: 7.2,
      flowRateM3Hr: 220.0,
      batteryPct: 87,
      signalStrengthDbm: -68,
      alertRemarks: "Turbidity elevation from seasonal sediment load along Varanasi Ghat stretch.",
    },
  },
  {
    id: "wms-nat-03",
    code: "WMS-IN-GJ-01",
    name: "Sabarmati Water Quality & Flow Station (Ahmedabad)",
    type: "Water Treatment / RO Plant",
    state: "Gujarat",
    district: "Ahmedabad",
    latitude: 23.0225,
    longitude: 72.5714,
    status: "ONLINE",
    installYear: 2022,
    readings: {
      status: "ONLINE",
      lastTransmission: "Today 10:40 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.4,
      phStatus: "NORMAL",
      tdsPpm: 640,
      tdsStatus: "NORMAL",
      turbidityNtu: 2.1,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.28,
      waterLevelDepthM: 5.1,
      flowRateM3Hr: 85.0,
      batteryPct: 96,
      signalStrengthDbm: -60,
    },
  },
  {
    id: "wms-nat-04",
    code: "WMS-IN-AS-01",
    name: "Brahmaputra Flood Stage & Hydro Gauge (Guwahati)",
    type: "River & Estuary Gauge",
    state: "Assam",
    district: "Kamrup Metropolitan",
    latitude: 26.1445,
    longitude: 91.7362,
    status: "ONLINE",
    installYear: 2023,
    readings: {
      status: "ONLINE",
      lastTransmission: "Today 11:30 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.1,
      phStatus: "NORMAL",
      tdsPpm: 195,
      tdsStatus: "NORMAL",
      turbidityNtu: 5.2,
      turbidityStatus: "HIGH",
      chlorineResidualMgL: 0.12,
      waterLevelDepthM: 11.8,
      flowRateM3Hr: 480.0,
      batteryPct: 93,
      signalStrengthDbm: -70,
    },
  },
  {
    id: "wms-nat-05",
    code: "WMS-IN-AP-01",
    name: "Godavari River Hydro-Telemetry Station (Rajahmundry)",
    type: "River & Estuary Gauge",
    state: "Andhra Pradesh",
    district: "East Godavari",
    latitude: 16.9891,
    longitude: 81.784,
    status: "ONLINE",
    installYear: 2022,
    readings: {
      status: "ONLINE",
      lastTransmission: "Today 10:50 AM (Demo Sync)",
      isSimulatedDemo: true,
      ph: 7.6,
      phStatus: "NORMAL",
      tdsPpm: 320,
      tdsStatus: "NORMAL",
      turbidityNtu: 2.4,
      turbidityStatus: "NORMAL",
      chlorineResidualMgL: 0.22,
      waterLevelDepthM: 8.5,
      flowRateM3Hr: 310.0,
      batteryPct: 95,
      signalStrengthDbm: -66,
    },
  },
];
